spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path:  /api/v1/


application:
  security:
    jwt:
      secret-key: 6519578981E4BAB1FBC7EBF3FFA97
      expiration: 8640000